proyecto26/react-native-inappbrowser

README.md
example/App.js
ios/RNInAppBrowser.m

This is for fixing issue #5 . With this change the status bar style can been manage from react native. This will keep the latest style from the app or you can example use the method for it. Example with the method.
```js
openInBrowser: flow(function*() {
try {
StatusBar.setBarStyle('dark-content')
yield WebBrowserServices.openUrl({ url: self.url });
} catch (error) {
Alert.alert(error.message);
}
}),
```

Let status bar been managed from the react-native side

---

README.md
android/build.gradle

Fixes many opened issues about support lib when building. Instead of excluding support lib packages and face another problems, change latest versions to sticky and configurable by main application.

supportLibVersion definition avoiding version collisions

---

RNInAppBrowser.podspec

Updates a minor bug carried across from #10.
The URL of the repository is wrong - it now reads this from the `package.json` file instead of hard coding it.

Fix the repository URL for podspec file

---

ios/RNInAppBrowser.m

Options mentioned in PR topic are not supported with iOS 9.x and causes app crashing if set. That is just check that those will be skip with iOS 9.
https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller/2274394-preferredbartintcolor
https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller/2274393-preferredcontroltintcolor

Avoid crashes with iOS 9 for skipping preferredBarTintColor and preferredControlTintColor

---

README.md

A little trick I found to restore the old bar style, when the browser is dismissed, since dismissing the browser doesn't trigger any rerenders the old bar style will otherwise get lost in most scenarios.

Provide example how to restore old status bar style

---

package.json

If react-native need to be as peerDependency, change it that if you don't use 0.55 which is quite old version, you don't get this  warn every time:
`npm WARN react-native-inappbrowser-reborn@1.3.12 requires a peer of react-native@^0.55.0 but none is installed. You must install peer dependencies yourself.`
For my testings, that works also without RN as peer dependency, or value as *, so I'm not sure if that needed at all here. But at least shouldn't warn users.

Fix peerDependency warning about react-native

---

index.d.ts

Fixes this error:
```
node_modules/react-native-inappbrowser-reborn/index.d.ts:32:18 - error TS2693: 'string' only refers to a type, but is being used as a value here.
```

Fix typing

---

README.md
android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java

Similar issue as https://github.com/proyecto26/react-native-inappbrowser/pull/45
Calling the `open` function twice could trigger the `EventBus.getDefault().register(this);` twice which would trigger:
```
org.greenrobot.eventbus.EventBusException: Subscriber class com.proyecto26.inappbrowser.RNInAppBrowser already registered to event
```
This makes sure we don't register again the browser instance

Fix EventBusException on Android

---

android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java

While build for Android, got this error:
> ### java compiler error
> error: package com.facebook.infer.annotation does not exist
We can replace Assertation library by using:
```
if (mOpenBrowserPromise == null) {
throw new AssertionError();
}
```
like here:
https://github.com/facebook/infer/blob/master/infer/annotations/src/main/java/com/facebook/infer/annotation/Assertions.java#L24

replace Assertation lib to AssertationError which already have

---

.npmignore
android/.npmignore
ios/.npmignore
package.json

> all Gradle wrapper files need to be excluded from distribution
I already have the folder in my project that used this library as a dependency.
so I add the folder into `.npmignore` to exclude it from release distributions.
you can take a look at the discussion on [this PR](https://github.com/kmagiera/react-native-reanimated/pull/463#issuecomment-552781215)
cc @friederbluemle

Exclude unnecessary file and folders from release distribution

---

CHANGELOG.md
example/yarn.lock
package.json

- Validate if the **type** of the auth result is different to `cancel` before to check the url of the last redirection from **Android**.
- Fixed issue getting the result of the auth redirection by using `AppState` to detect **Android** Activity `OnResume` event once.

Release v3.3.2

---

CHANGELOG.md
example/ios/Podfile.lock
example/ios/example.xcodeproj/project.pbxproj
ios/RNInAppBrowser.h
ios/RNInAppBrowser.m
package.json

We're having issues with previous versions of iOS and Xcode building the last changes of iOS 13
Fixing conditional compilation and using Pragma to ignore build warnings.
Fixes/Implements/Closes:
- https://github.com/proyecto26/react-native-inappbrowser/issues/125
- https://github.com/proyecto26/react-native-inappbrowser/issues/126
- https://github.com/proyecto26/react-native-inappbrowser/issues/128

Hotfix iOS 13 build issues

---

ios/RNInAppBrowser.m

https://github.com/proyecto26/react-native-inappbrowser/issues/131
Swipe to dismiss gesture is disabled for modal.

Disable swipe to dismiss gesture for modal

---

CHANGELOG.md
README.md
example/ios/Podfile.lock
example/ios/example.xcodeproj/project.pbxproj
ios/RNInAppBrowser.h
ios/RNInAppBrowser.m
package.json
yarn.lock

- Disable swipe to dismiss gesture for modal by [@frankyjuang](https://github.com/frankyjuang) ([#134](https://github.com/proyecto26/react-native-inappbrowser/pull/134)).

Release v3.3.4

---

README.md
index.d.ts
index.js
ios/RNInAppBrowser.m

Hello, 
Actually, on iOS 12+, when you login, the cookie is kept until the app is killed. 
Since iOS 13 it's possible to make session ephemeral. 
With this option prefersEphemeralWebBrowserSession, the cookie is killed when tab browser is closed. 
Pros : 
- no need to logout manualy users (for account switch for example) 
Cons : 
- user should reconnect each time the tab is presented.
It fix https://github.com/proyecto26/react-native-inappbrowser/issues/76 , on iOS 13.
TODO : Improvement : make this parameter as an option 
Best Regards
Fixes/Implements/Closes #[Issue Number].

Supports ephemeralWebBrowserSession on iOS 13

---

package.json
yarn.lock

Use fixed versions for `react` and `react-native`.
One version of `react-native` is always tightly coupled with exactly one version of `react`. They can't go out of sync, or things will likely break.

Fix react and react-native deps

---

android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowserModule.java

Add `@ReactModule` annotation, this will eventually be used by TurboModules annotation processor.

Add `@ReactModule` annotation

---

ios/RNInAppBrowser.m

I am getting exception is this place and it seems like this check is done in many other places but here.

Add a null check for redirectResolve in safariViewControllerDidFinish

---

README.md

fix(readme): update modalPresentationStyle to 'fullscreen' to fix use case of pasting code from readme and seeing native crash
For my use case, pasting readme code into my project crashes immediately on attempting to open the browser
found this: https://github.com/proyecto26/react-native-inappbrowser/issues/130#issuecomment-566569216
I'm not familiar with *why* only fullscreen is supported in my use case. It may or may not make sense to update readme. Sending PR as it is really small change with a big potential impact. Apparently prettier changed some whitespace too.
```
System:
OS: macOS Mojave 10.14.6
CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Memory: 93.93 MB / 16.00 GB
Shell: 5.0.17 - /usr/local/bin/bash
Binaries:
Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
Yarn: …
```

fix(readme): update modalPresentationStyle to 'fullscreen'

---

android/build.gradle

running mergeExtDexDebugAndroidTest task failed. fixed it as described [here](https://stackoverflow.com/questions/49512629/default-interface-methods-are-only-supported-starting-with-android-n/49525685#49525685)
Tried to run detox build for android in my project.
This library failed with:
```
> Transform artifact browser.aar (androidx.browser:browser:1.3.0-alpha01) with DexingTransform
AGPBI: {"kind":"error","text":"Static interface methods are only supported starting with Android N (--min-api 24): androidx.browser.trusted.TrustedWebActivityDisplayMode androidx.browser.trusted.TrustedWebActivityDisplayMode.fromBundle(android.os.Bundle)","sources":[{}],"tool":"D8"}
> Task :react-native-inappbrowser-reborn:mergeExtDexDebugAndroidTest FAILED
```
Now I can run detox build in my root project …

fixing mergeExtDexDebugAndroidTest task

---

android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java

- [ x] The PR title follows our guidelines: https://github.com/proyecto26/react-native-inappbrowser/blob/master/CONTRIBUTING.md#pull-request-process.
- [ x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x ] All existing tests are passing
- [ x] Tests for the changes are included
A system popup will be shown if the device has installed multiple browsers or apps that can handle CustomTabsIntent service.
If Chrome is available, then Chrome is the highest priority browser selected, otherwise, the first browser which supports CustomTabsIntent is chosen.
Fixes #149 #107
Implements #86

add default browser for custom tab if any

---

RNInAppBrowser.podspec

The iOS is depending on `React` Pod
This fixes the Xcode 12 compatibility issue. More info can be found here https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
This fixes #187

Fix Xcode 12 compatibility.

---

.npmignore
CHANGELOG.md
README.md
index.d.ts
package.json

- Removed `files` option from **package.json** to use `.npmignore` instead.
- Added `hasBackButton` to **index.d.ts** for typescript by [@sharifhh](https://github.com/sharifhh) ([#200](https://github.com/proyecto26/react-native-inappbrowser/pull/200)).

Release 3.5.1

---

ios/RNInAppBrowser.m

openAuth crashed when going to be closed and then press the cancel button.
The completionHandler was called, then redirectResolve to be null by flowDidFinish. After that completionHandler be call again by press the cancel button.
redirectResolve is null, and so crash.
No more crash.
Fixes/Implements/Closes #186.

#186 openAuth crashed when going to be closed and then press the cancel button

---

.babelrc
example/App.js
example/ios/Podfile
example/ios/Podfile.lock
example/ios/example.xcodeproj/project.pbxproj
ios/RNInAppBrowser.m

Exception with invalid scheme is thrown
The scheme will be escaped by default
Fixes/Implements/Closes #256
I tried testing this change with the example but there occurred just more errors. I fixed the flipper and babbel one and then gave up.
I hope everything will work. I'm not very familiar with iOS so don't bash me if I made something wrong. I just need the fix.

Fix invalid scheme with iOS 14.5

---

ios/RNInAppBrowser.m

Malformed urls is causing the app to crash since the Safari View Controller does not work with all urls. 
Fixes/Implements/Closes #189.
Based on the description okwast gives [here](https://github.com/proyecto26/react-native-inappbrowser/issues/189) a try catch block is added around the initialization of the SFSafariViewController.
With this change exceptions thrown by the native layer can be handled at the react native layer.

Add try catch block to Safari View Controller logic

---

types.js

Flow are complaining about the exact types, this small PR should fix this issue
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/react-native-inappbrowser-reborn/types.js:65:35
Flow cannot determine a type for InAppBrowserOptions [1]. InAppBrowseriOSOptions [2] is inexact, so it may contain
toolbarColor with a type that conflicts with toolbarColor's definition in InAppBrowserAndroidOptions [3]. Can you make
InAppBrowseriOSOptions [2] exact?.
62│   showInRecents?: boolean,
63│ };
64│
[1] 65│ export type InAppBrowserOptions = {
[3] 66│   ...InAppBrowserAndroidOptions,
[2] 67│   ...InAppBrowseriOSOptions
68│ };
69│
70│ export type AuthSessionResult = RedirectResult | BrowserResult;
71│
```
Fixes/Implements/Closes #[Issue Number].

fix(flow) - Make InAppBrowserOptions exact typed

---

CHANGELOG.md
android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java

Fix `Build failed. Error cannot find symbol builder.setNavigationBarColor` error for Android Support
Android Support is not working with the new methods of `CustomTabsIntent.Builder` for `AndroidX`.
Detect if the method exists before to invoke the function to avoid build issues by using Reflection.
Fixes/Implements/Closes #279.

fix(android): 279 - Fix error cannot find symbol

---

android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java

- [x ] The PR title follows our guidelines: https://github.com/proyecto26/react-native-inappbrowser/blob/main/CONTRIBUTING.md#pull-request-process.
- [ x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
Fixed: #284

fix(android): Fix error com.facebook.react.bridge.NoSuchKeyException

---

index.d.ts
types.js

This PR export the types `InAppBrowseriOSOptions`, `InAppBrowserAndroidOptions`
Allows typing the platform specific options separately
```
const inAppBrowseriOSOptions: InAppBrowseriOSOptions = 
enableBarCollapsing: false,
};
const inAppBrowserAndroidOptions: InAppBrowserAndroidOptions = {
forceCloseOnRedirection: false,
showInRecents: true,
};
const inAppBrowserOptions: InAppBrowserOptions = {
...inAppBrowseriOSOptions,
...inAppBrowserAndroidOptions,
};
```

Export options types

---

ios/RNInAppBrowser.m

On iOS, calling `openAuth` with undefined/null for `redirectUrl` will crash the app. This issue was recently introduced in [this commit](https://github.com/proyecto26/react-native-inappbrowser/commit/b35ef11f48c072971ec61049dc1370678db2dac1#diff-4ad743dcf362c4be43c8798f2c973b620a77dfabbd789c60f4574a416dcd03b8) where the scheme is being extracted from the redirect url. The result is that `escapedRedirectURL = "<null>"` which is not a valid URL scheme.
```
ExceptionsManager.js:179 Exception '*** -[NSURL initWithString:relativeToURL:]: nil string parameter' was thrown while invoking openAuth on target RNInAppBrowser with params (
"https://xxx.xxx.amazoncognito.com/logout?client_id=xxx&logout_uri=myscheme%3A%2F%2Fpath",
"<null>",
...
```
Don't attempt to extract the scheme from `redirectUrl` …

Prevent iOS crash when redirect url is null

---

android/src/main/AndroidManifest.xml

All apps that are using `react-native-inappbrowser` dependency automatically include the dangerous `QUERY_ALL_PACKAGES` permission and [need to explain](https://support.google.com/googleplay/android-developer/answer/10158779?hl=en#zippy=%2Cpermitted-uses-of-the-query-all-packages-permission) why they are using it or the apps will be removed from July 2022. 
We can safely remove this permission, as we only need to query the browsers that support custom tabs and having 
```
<intent>
<action android:name="android.support.customtabs.action.CustomTabsService" />
</intent>
```
is enough for that.
See https://developer.android.com/training/package-visibility/use-cases#open-urls-custom-tabs
> However, you might want to [check whether the device has a browser that supports Custom …

Remove QUERY_ALL_PACKAGES permission

---

android/build.gradle
android/src/main/AndroidManifest.xml
example/android/app/src/main/AndroidManifest.xml
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties

Fixes  #327.
Upgrade example and the library project to compile with Sdk version 31 (Android 12). This also added required `exported` flag in `AndroidManifest.xml`. I believe there's no reason for external apps to open `ChromeTabsManagerActivity`, so the `exported` flag here should be `false`.
BREAKING CHANGES: By default, it will now use Android 31, so the library user have to upgrade if they don't provide required gradle ext values. I believe this won't impact much since most react native project already specify those sdk versions. Or they could also use override version in `AndroidManifest.xml`
```xml
<uses-sdk android:targetSdkVersion="{VERSION}"
tools:overrideLibrary="com.proyecto26.inappbrowser"/>
```

Upgrade build configuration to use sdk 31 instead

---

utils.js

For React Native's `Linking` and `AppState` APIs, the deprecated `removeEventListener()` calls had been used before.
Both `Linking.addEventListener()` and `AppState.addEventListener()` return an event subscription object containing a corresponding `remove()` method. They are being used in `utils.js` now.
Fixes/Implements/Closes #296.
No breaking changes
@jdnichollsc I am a TypeScript person and have never worked with flow before. Please check the flow types whether they are still correct.

Remove deprecated `removeEventListener()` calls

---

android/build.gradle

App won't compile.
Bumped org.greenrobot:eventbus dependency causing issues since JCenter is deprecated.
`implementation 'org.greenrobot:eventbus:3.+'` to `implementation 'org.greenrobot:eventbus:3.1.0'`

🔨Upgraded dependency org.greenrobot:eventbus to 3.1.0 due to build issue

---

README.md
android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java
example/utils.js
index.d.ts
types.js

There is no way to add referrer intent extra in android.
Added `includeReferrer` options for Android to add your package name as referrer when launching in in app browser:
See: https://developer.chrome.com/docs/android/custom-tabs/best-practices/#add-your-app-as-the-referrer
Fixes #86

[Android] Add includeReferrer to allow adding android package name as referrer for website to track

---

CHANGELOG.md
README.md
index.d.ts
ios/RNInAppBrowser.m
package.json
types.js

Unable to define the size of `formSheet` modals on iPad
Added new prop to allow for custom sized formSheet modals on iPad. 
Implements #330.
Migration steps:
- No migration steos needed, new prop is optional. 
https://user-images.githubusercontent.com/18077159/156228925-e75433d2-4a04-4a45-9f31-1fedcf6421f8.mov
https://user-images.githubusercontent.com/18077159/156228944-e5a6ce5c-0357-4920-9dbf-0d44935fc17b.mov

iOS: Add formSheetPreferredContentSize prop to allow for custom sized formSheet modals

---

README.md
android/build.gradle
android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowser.java
android/src/main/java/com/proyecto26/inappbrowser/RNInAppBrowserModule.java
example/App.js
example/android/app/src/main/java/com/example/MainActivity.java
index.d.ts
index.js
utils.js

There was no way to optimize the performance for Android.
Exposes `warmup` and `mayLaunchUrl` that allows optimization. 
Fixes #84

[Android] Add mayLaunchUrl and warmup methods

---

ios/RNInAppBrowser.m

Currently there is no way to distiguish between user canceled and canceled from an error.  Adding the error description allows for a better user experience.
Currently when openAuth is terminated by error or by the user hitting cancel, the result is the same and type: cancel is returned
Example - {"type":"cancel"}
This change simply adds the error description if it exists so a better user experience can be achieved.
Example - {"type":"cancel","description":"The UIWindowScene for the returned window was not in the foreground active state."}
Fixes/Implements/Closes #[Issue Number].

Add error description to openAuth response

---

android/build.gradle

The investigation is available here: https://github.com/proyecto26/react-native-inappbrowser/issues/398
This exact problem was already addressed multiple times and we still get surprised by failing builds (#298, #386 ). I think it's worth to set a fixed version to prevent this kind of surprise in the future. 🙏
Fixes androidXVersion to 1.5.+ which is the latest before the kotlin 1.8.0 issue...
Fixes/Implements/Closes #398.

fix androidXVersion to prevent build fails
